# Generated by Django 3.2 on 2021-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
