# Generated by Django 3.2 on 2021-05-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('LN', 'Light novel'), ('WN', 'Web novel')], default='LN', max_length=2, verbose_name='Tipo')),
                ('structure', models.CharField(choices=[('VOL', 'Volumes'), ('ARC', 'Arcs'), ('CHA', 'Chapters')], default='VOL', max_length=3, verbose_name='Estructura')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(null=True)),
                ('user_id', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_object', to='contenttypes.contenttype')),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_user', to='contenttypes.contenttype')),
            ],
        ),
    ]
