# Generated by Django 3.2 on 2021-05-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20210511_2100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likes',
            name='unique_like',
        ),
    ]
