# Generated by Django 3.2 on 2021-05-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_remove_likes_unique_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='object_content_type',
            new_name='content_type',
        ),
    ]
