# Generated by Django 3.2 on 2021-05-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_rename_object_content_type_likes_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
