# Generated by Django 3.2 on 2021-05-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0002_alter_like_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'get_latest_by': 'creation_date'},
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='likes_object', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('content_type', 'object_id')},
        ),
    ]
