# Generated by Django 3.2 on 2021-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20210512_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
