# Generated by Django 3.2 on 2021-05-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='content',
            field=models.JSONField(),
        ),
    ]
