# Generated by Django 3.2 on 2021-05-15 12:13

from django.db import migrations
import django_tiptap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fansubs', '0002_alter_contrib_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='content',
            field=django_tiptap.fields.TipTapTextField(),
        ),
    ]
