# Generated by Django 3.2 on 2021-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansubs', '0003_alter_contrib_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='content',
            field=models.TextField(),
        ),
    ]
